name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  deploy-client:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install TailwindCSS
        run: deno install --dev npm:tailwindcss npm:@tailwindcss/vite
        working-directory: ./client

      - name: Install Tailwind forms plugin
        run: deno install --dev npm:@tailwindcss/forms
        working-directory: ./client

      - name: Install Skeleton
        run: deno install --dev npm:@skeletonlabs/skeleton@next npm:@skeletonlabs/skeleton-svelte@next
        working-directory: ./client

      - name: Install Jose
        run: deno install --dev npm:jose
        working-directory: ./client
          
      - name: Load dependencies
        run: deno install --allow-scripts
        working-directory: ./client
        
      - name: 'Create env file public'
        run: |
          touch .env.production
          echo PUBLIC_API_URL=${{vars.PUBLIC_API_URL}} >> .env.production
          echo PUBLIC_INTERNAL_API_URL=${{vars.PUBLIC_INTERNAL_API_URL}} >> .env.production
          echo COOKIE_KEY_AUTH=${{vars.COOKIE_KEY_AUTH}} >> .env.production
          cat .env.production
        working-directory: ./client

      - name: 'Create env file private'
        run: |
          touch .env
          echo JWT_SECRET=${{secrets.JWT_SECRET}} >> .env
          cat .env
        working-directory: ./client
          
      - name: Build client
        run: deno run --env-file=.env.production build
        working-directory: ./client
        
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: k-zhou-web-dev-aalto
          entrypoint: index.js
          root: ./client/build
          
  deploy-server:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
        
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kzhou-webdev-aalto-server
          entrypoint: app.js
          root: ./server
